### ISSUE TITLE
FUS Now Requires a Valid IMEI or Serial Number 

### ISSUE THREAD

**Issue by TheRealMrWicked** [chenxiaolong/samfusdl#30]
Samsung has made changes now requiring a valid IMEI or Serial number to download Firmware from their servers.

Bifrost has been updated and works properly, see [this commit](https://github.com/zacharee/SamloaderKotlin/commit/b1d003065835d15e9445b3bd53cf50183274e275) for the implementation.

I know the solution is simply to take a command line argument and use that in the FUS request but I am too lazy to implement it.

Thank you - MrWicked

**Comment by chenxiaolong** [comment]
This is already supported since version 0.1.8 with the `-i` (`--imei-serial`) option. I forgot to document that in the README though--I'll do that after work today.

**Comment by RealMrWicked** [comment]
I tested the program and I works properly, thank you for the update.

Also you need to add the argument in the error message, so users know it needs to be passed.

That is why I did not know you already implemented it.

Thank you for you help.
